### ISSUE TITLE
Merge markers are casuing grunt styles to not work

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/wd_s#114]
![](https://cldup.com/dHhnJnW7qW.png)

I've been getting this error a lot when I have a merge conflict on Gruntified files. I can delete them and re grunt styles and I'm good. I'm not 100% sure how to fix it. The merge conflict markers are in the minified files (which always happens) but them trying to re-grunt styles them fails with this error.

**Comment by efuller** [comment]
I've been getting these as well.

**Comment by briannaorg** [comment]
I got this once yesterday, but it turned out that when I selected all the style-dot files to resolve them, I had missed the minified one. So I re-resolved it to "mine", then ran grunt styles again without having to delete anything.

This likely not correct, but it reduces the chances I'll screw up a merge and not get my style changes in - when I need to merge from my feature branch to master, I checkout master and pull the latest, then I checkout my feature branch and merge the latest master into it, resolve all conflicts to "mine", run grunt or grunt styles, then checkout master and merge my feature branch to it without conflicts. If I try and resolve conflicts on the local copy of master, it usually doesn't resolve correctly the first time I grunt styles after that, so I try to keep the conflicts off master and on my feature branch instead.

**Comment by gregrickaby** [comment]
This is happening because we're creating a minified file with every compilation. We used to just run `grunt sass` and then we'd manually have to run `grunt styles` before pushing up. Unfortunately, Git will never ever be able to figure out how to merge a minified file.

**Comment by gregrickaby** [comment]
We've voted to leave things as is. You can resolve the conflict using "resolve using theirs" and re-running `grunt styles`
