### ISSUE TITLE
Create a generic, re-usable Navicon/Hamburger Nav

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#137]
We use a navicon/burger on almost every build. Let's finally get one in here as a baseline.

**Requirements:**
- Must use an SVG navicon icon
- Must have a slide-out drawer
- Must be accessible and pass 508c testing
- Visible from phone-portrait -> tablet-portrait

Bourbon Refills has code for this, and I've used it on a few projects as well. http://refills.bourbon.io/components/#sliding-panel

Thoughts?

**Comment by coreymcollins** [comment]
Or, we could totally abandon the hamburger icon like we've talked about internally and come up with a different solution for mobile menus since the burger is trash anyway.  Just a thought!

**Comment by colorful-tones** [comment]
I would suggest we add "Menu" next to icon, or below.

Also, it seems that not all sites use off-screen nav paradigm, but also toggling of menu. Therefore, I would not suggest we map to one pattern. Maybe we could even develop partial for either/or, and just a matter of adding class for which one you choose?

**Comment by gregrickaby** [comment]
We can't abandon it. It was in almost every comp from 2015. I expect that trend to continue, plus the amount of hours we burn on re-creating this functionality again and again is appalling. There is no "one size fits all" solution, but having some baseline sass and javascript in here will go a long way.

**Comment by coreymcollins** [comment]
Yes, it was in almost every comp from 2015 but we were also in control of a lot of those comps.  It was there because put it there.  I know we've all talked about how the burger icon isn't really the best and would like to replace it, but we'll never replace it if we don't take steps to find something new to use in its place.

**Comment by gregrickaby** [comment]
@simonwebdesign @bezierer I'd like both you to weigh in here. What are you thoughts on abandoning the Navicon in favor for something else?

**Comment by efuller** [comment]
I've worked heavily on menus(mega menus) on a few recent projects and overall I think it's a great idea to create a better base solution.

One idea I had was to create our own custom jQuery plugin that would allow for configuration.

One config example could be whether or not to provide toggle buttons for menus that have both top-level links plus sub-menus on mobiles and tablets.

**Comment by colorful-tones** [comment]
Small screen navigation is an ongoing discovery process for users, designers and developers. Yes, I believe small additions can be made to enhance the existing out-of-box "Hamburger" menu residual from original _s, but feel this is an area we want to keep too much opinionated code out of. 

I would suggest we start a pattern library (drop-ins) for extending wd_s in separate repo. There we could do many different paradigms for menus, search, forms, responsive `<table>`, etc.

**Comment by bezierer** [comment]
@gregrickaby For me personally, if the Information architecture will allow it, I always like investigating other patterns besides the hamburger. I've been observing a lot of big players doing the same. I know on AllClear ID and Office we skipped the hamburger in favor of other patterns that keep the nav in view at all times.

Here are some different patterns that we could discuss on the designer call:
- http://www.theguardian.com/us – resize the browser or check it out on mobile to see this neat effect.
- http://www.bbc.com/news – as you size down, any links that don't fit in the nav get added to the More dropdown—in the last week they added a hamburger on mobile instead of carrying the effect all the way down which is interesting.
- There are also the bottom menus like we did on Office that are fixed to the bottom of the screen. You see those  in a lot of apps like Facebook.

And there are others I could add before the call when I have a little more time.

So I don't think we should completely abandon the hamburger because it does have it's merits, but I'd also be cautious about letting it become the default when we're in control of the comps.

**Comment by colorful-tones** [comment]
I'm a fan of the Horizontal Overflow pattern, which I think The Guardian (@bezierer mentions) riffs on: http://codepen.io/jordanmoore/pen/pnlAi

It keeps the menu prominent, while forcing stakeholders to identify their navigational priorities. Which seems like a win for everyone (users, devs, stakeholders, etc.)

**Comment by colorful-tones** [comment]
Here are some Navigation patters for reference: https://bradfrost.github.io/this-is-responsive/patterns.html#navigation

**Comment by bezierer** [comment]
I think we should try to identify 3 go-to patterns, and for anything not fitting the mold of those 3 we could investigate other patterns. It could be something like:
- Default/we don't control over comps: Use the hamburger.
- Sites with more pages: Use the Overflow pattern.
- Sites with more limited IA (~1-6 pages) use the bottom or top fixed nav pattern.

That way we're not reinventing the wheel each time but we're not falling into a routine/default either.

**Comment by coreymcollins** [comment]
I really like the horizontal overflow pattern as well.  I think it works pretty well, or can work pretty well, if styled nicely.  The main hurdle there is to give enough of an indicator to the user that they can swipe horizontally through to additional menu items.

What I like about it is that it doesn't take the user away from anything.  They don't have to click a button and obscure the rest of the page - they can just scroll through menu items similar as to how they would swipe up and down a page anyway.  Get those thumbs workin'!

**Comment by bezierer** [comment]
Also consider: stats show that with the hamburger **a lot** of users require extra indicators to know that it hides the menu items as well, and even then it's no guarantee. So even though the overflow requires some extra indication to users, _at least_ it has the backup of actually showing some links to the user by default.

**Comment by simonwebdesign** [comment]
Recently been kicking around the idea of Hamburger menu usage. Seems ironic to me a convention that literally purports navigation ease of use fails at it’s own convention. Was going to blog about this. 

The Hamburger was like a one side of the navigation pendulum that designers and devs adopted without really waiting for data. Now designers and dev want to take the pendulum all the way to abandoning it - that's understandable. 

Thanks to seminal work done by LukeW we have at the very least small samples of qualitative data that say the Hamburger is not useless in the right context. As well, the adaptive versus responsive approach is a huge barrier here. 

I propose we give what the users want - mobile patterns not responsive per se. I am talking about something very close to what Cameron bullet pointed. Look at the screen shot from left to right in the screen shot. I think we should have everything on the footer in including the burger, because that is where your thumb is. 

![screen shot 2015-12-21 at 12 37 44 pm](https://cloud.githubusercontent.com/assets/4624284/11937195/cbb4a236-a7e0-11e5-9b9e-a0ebe3fec091.PNG)

**Comment by gregrickaby** [comment]
Really like what @simonwebdesign has shared, especially the 4th image. My question would be: how do we "BEST" sniff out which menu system to display? User Agent? (no) Feature? (better) Screen width via JS? (probably best)

**Comment by gregrickaby** [comment]
Had some time to play. I started an "overflow" menu. My initial thought is: it makes us look lazy when the navicon halfway covers a nav item. 

![screencast](https://dl.dropboxusercontent.com/s/f7n53rzyar9zw5d/wd_s-overflow-nav.gif?dl=0)

Committed to this branch: https://github.com/WebDevStudios/wd_s/commits/feature/overlfow-navicon

**Comment by coreymcollins** [comment]
I'm not really a fan of that either.  I lean more toward the horizontal-swiping menu without an extra button to push.

Ideally, we could make sure clients only have 4-6 main nav links and use a fixed footer navigation like many apps use, but I know that's a perfect world scenario and we don't often wind up in one of those.

**Comment by colorful-tones** [comment]
Yeah, I've never seen the Horizontal Overflow approach with the "Menu" button still there. What would be the purpose/function of leaving the "Menu" button? I'm not a big fan. As I mentioned above I'm a fan of this style: http://codepen.io/jordanmoore/pen/pnlAi. 

The one in @simonwebdesign that shows menu sticky to bottom seems to be the "Priority+" paradigm/method: http://codepen.io/Dreamdealer/pen/waVzmK

**Comment by simonwebdesign** [comment]
@coreymcollins Maybe if it's just part of the process we can do that from an IA perspective without much fuss. If you think about it, clients may already have an expectation of a hamburger. So delivering something more thoughtful could benefit all, but especially the clients' users. So give the clients a choice, hamburger or a hybrid.

@colorful-tones  What I am proposing is have a hamburger with whatever the depth of navigation is in a normal hamburger as is - the kitchen sink. Put it on the footer with the top 4 main values represented with icons. Put everything at the footer. Because unless a user has a circus freak 5 inch thumb a menu on the top of an iPhone 6 Plus (or comparable android) makes zero sense. The industry is already headed toward the footer (maybe not to this extent), because of thumb proximity. 

Some clarification, what I am proposing is only for mobile and specifically according to how most users hold phones when using a website i.e. one hand thumb touches.

**Comment by simonwebdesign** [comment]
Further clarification, I don't literally mean this is a footer. I want to describe it's position. It is the main navigation that sticks to the bottom of the viewport.

**Comment by colorful-tones** [comment]
This is a neat, although not entirely encompassing and ground-breaking solution: http://lucidlemon.github.io/paradeiser/

**Comment by gregrickaby** [comment]
While we debate (which I love) the final plan of action, I've brought back the old menu toggler from _s. The only difference is the navicon SVG and some light styling. 

Currently, wd_s has a broken nav toggle. This simply fixes that, plus gives us an ultra-basic mobile menu starting point. For the time being, I want to merge this in. 

Commits here:
https://github.com/WebDevStudios/wd_s/commits/feature/basic-navicon

![screencast](https://dl.dropboxusercontent.com/s/b6qzm66jzhnr8xo/wd_s-basic-navicon.gif)

**Comment by gregrickaby** [comment]
Per our discussion on this week's call,  here are the requirements for our new mobile menu:
- We will model/fork our new mobile menu based on Paradeiser http://lucidlemon.github.io/paradeiser/
- It will appear on page load, and while scrolling and disappear when user stops scrolling
- It will display the first 4 items out of the box, but allow the client to control which items display by creating a new “Mobile” menu in WordPress Menu Manager
- Add body class if Mobile menu exists
- “More” items might be off-canvas rather than centered?

I also want to note that our two primary designers (@simonwebdesign @bezierer) will set the pace and educate clients on why our menu solution is better than say, a traditional hamburger. While the client always has the final say - we (WDS) will do our best to guide them in this direction. 

If I left something out, just add it here. Thanks @coreymcollins

**Comment by coreymcollins** [comment]
I think we have bullet point two backwards - it should probably disappear while scrolling and appear when stopped, otherwise the user would never be able to click a menu item.

**Comment by gregrickaby** [comment]
This is what happens when you write notes by hand :cry:

**Comment by gregrickaby** [comment]
This was merged in! Closing!
