### ISSUE TITLE
Create Gulp based theme generator 

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#153]
Based on both conversations internally and on #64, @briannaorg is going to attempt to create a theme generator using Gulp. What I'd like to see is someone clone/download wd_s and then type: `npm install && gulp wd_s` to get spun up.

Following the current search/place instructions (as listed in the readme), here are some requirements:
- [ ] Prompt user with question about new project name
- [ ] Find/replace all instances of _s with the new project name

**Comment by gregrickaby** [comment]
Now that https://wdunderscores.com is up and running; do we still want to pursure this @briannaorg?

**Comment by briannaorg** [comment]
I assumed https://wdunderscores.com was intended to replace this. The results of my work over here basically took us to the same place as the grunt init generator for wd_s that is already working - instead of a simple JS-based search and replace in the same directory using gulp tasks, we would have to have the files in a separate directory and write a Slush generator for it. Which is fine, but the grunt init generator already does this, https://wdunderscores.com already does it, it's not really useful if it forces us to change up the directory structure so it's difficult to sync to the master _s repo. 

So no, I don't think we want to pursue it, it doesn't offer anything we don't already have, it just adds maintenance difficulty.

**Comment by gregrickaby** [comment]
👍
