### ISSUE TITLE
Sass Linter

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#157]
Would be cool to run our Sass through a linter before compiling. Run it against a list of WP & WDS code standards. It could also check for misspellings, etc...

**Comment by efuller** [comment]
I am going to test this package - https://www.npmjs.com/package/gulp-sass-lint

**Comment by efuller** [comment]
Branch: [feature/gulp-sass-lint](https://github.com/WebDevStudios/wd_s/tree/feature/gulp-sass-lint)

I was able to get an initial, basic configuration setup. Right now, linting is only checking for `property-sort-order`. Rules can be added as necessary.

Here are some bullet points of what was done:
- `gulp-sass-lint` was added as a dependency
- added `.sass-lint.yml` - configure the rules here
- added `sass:lint` Gulp task - made it part of `styles` task
- excluded `_normalize.scss` and the `animate` folder from being scanned

**Comment by gregrickaby** [comment]
Ok, took the ball and ran down to the 1 yardline. I believe I've got the lint rules matching both WDS and WP standards. I'm sure there will be improvements, but for now, this will alert a dev if they miss something! :smiley: 

This has been merged into: https://github.com/WebDevStudios/wd_s/tree/feature/gulp. Which I plan on merging into master on Monday.

Also, we'll need to create another issue to clean up these warnings. Haha!

![screenshot 2016-02-19 15 33 35](https://cloud.githubusercontent.com/assets/200280/13189644/3c156382-d71e-11e5-983f-fd3c2fcba7b4.jpg)

**Comment by colorful-tones** [comment]
I cleaned up as many Warnings as I could. I also [altered the config to allow-rgba: true](https://github.com/WebDevStudios/wd_s/commit/7389713e6f592788d733f77a31b4c89ac1ed5cb7) for no-color-literals, otherwise, we would not be able to use rgba unless it was inside a variable or map-list. Basically, this was not allowed: 

```
.rgba {
    color: rgba(255, 255, 255, .3);
}
```

There are more than a dozen Warnings left, but I was not sure how to handle, and configuration may be set a bit too aggressive in regards to shorthand hex values, as the _colors.scss is getting a bunch of false-negative matches.

**Comment by gregrickaby** [comment]
This was merged in with Gulp. https://github.com/WebDevStudios/wd_s/commit/b3133604b8b69804058cd70cad2e65d53ecf152d
