### ISSUE TITLE
Add modal support

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#170]
I'd like to discuss this, specifically our requirements. Several projects lately need modals. 

We have two CodePens for modals:

This one (which is based on Refills)
http://codepen.io/webdevstudios/pen/MKGXLx

This one (which supports multiple modals and media)
http://codepen.io/webdevstudios/pen/GZbRyL/

**Comment by coreymcollins** [comment]
Added!

Branch is [feature/modals](https://github.com/WebDevStudios/wd_s/tree/feature/modals)

Used the CodePen link above for [multiple modals](http://codepen.io/webdevstudios/pen/GZbRyL/), as the first one is now deprecated.

I updated some of the JS here as well.
- Updated some of click calls to use `$( 'body ').on( 'click', '.element', app.functionName )` rather than listening for a click on the element itself. Good writeup on this [in this blog post](http://www.pdiniz.com/why-you-should-always-use-jquerys-onclick-instead-of-click/)
- Escape to close the modal was working but was not killing the video; rather, it was just hiding the modal and the video would continue playing. Updated this to in fact use the same closing function as the close button utilizes.
- Added a click listener for outside of the modal content container so clicking outside of the container will also close the modal.
- Updated the `closeModal` function to look for the modal with the `.modal-open` class for better extensibility with the Escape and "click outside" functions

<img width="1029" alt="screenshot 2016-07-29 11 54 03" src="https://cloud.githubusercontent.com/assets/954724/17254531/36f1cdda-5583-11e6-86a0-cd5f6b742db1.png">
