### ISSUE TITLE
Create basic styles for ancillary pages like 404/Search/Archives etc...

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#175]
Based on our FED call on June 30th, this pages always seem to come up in QA. Let's add some super basic styles so these pages look less terrible out of the box.

**Comment by ImBigWill** [comment]
These actually are decent out of the box with wd_s currently. I wonder if my thoughts on this were project specific making things seem like they were wonky. However I did remove the extra widgets from the 404 page as discussed and made a small change on archives so that leave a comment text didn't run into the category links. There are probably more things that could be adjusted, but I didn't want to get too specific. I think Allison is working on a fix for the excerpt that would adjust the only thing on the search results page which is the default [...] excerpt text. 

Branch:
**feature/ancillary-page-base-styling** 

Before Screenshot on archive:
https://www.dropbox.com/s/hvk4h23znqepxj7/Screenshot%202016-07-29%2013.36.26.png?dl=0
