### ISSUE TITLE
Add equal height cards to wd_s

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#213]
This is on every project. Let's just bake it in.

**Comment by gregrickaby** [comment]
Use the HTML markup from http://refills.bourbon.io/ cards and HTML5 it!

**Comment by allisonplus** [comment]
_Branch:_ https://github.com/WebDevStudios/wd_s/tree/feature/cards-equal-height

Created template tag  `_s_get_card_` that gets called within `_s_get_card_loop` (within extras.php).
Basic stylings living within `/modules/_card.scss`

(Co-created with Jo and Carrie.) Would be interested to hear any thoughts about naming, organization, etc. Heads up that this is using the template-tags file BEFORE the phpcs branch(es).

Screenshot is when you use:
`<?php echo _s_get_card_loop( array( 'num_cards' => '3', 'num_post' => 6 ) );  ?>`

![screen shot 2016-11-04-cards](https://cloud.githubusercontent.com/assets/10225971/20023670/0126d8da-a2b8-11e6-8721-0e96533a2f49.jpg)

**Comment by colorful-tones** [comment]
One suggestion I have is changing the naming convention to "cards" since that is what this feature is: cards. So `_s_get_card_loop` would be `_s_get_cards_loop` and Sass partial `_card.scss` would be `_cards.scss` and any other places that are pertinent. 

If I were to hop in to a project and hadn't known anything about this and needed to apply styling to the cards. When perusing the Sass folders for the appropriate partial, and saw `_card.scss` I would assume that the partial is just for an individual card's styling, and not for _all_ cards. 

Just a thought.

**Comment by carrieforde** [comment]
Having worked a lot more with cards and all that jazz, I'd love to see this broken out a bit further so it's more extensible:
1. Generalize the get_cards (I don't * think * we need loop in the name) function so that allows us to pass in an array of arguments, which might include `post_type`, `posts_per_page`, `category_name`, etc., as well as a `template_part` (which basically specifies which template part to pull).
1. Move the markup for the card to a folder/file within `/template-parts/`. I'd love to see `/template-parts/cards/` as a directory. Then, in the `get_cards` function, you can call `get_template_part( $args['template_part'] )`. This allows us to grab whatever flavor of markup we want with on query function. :D

**Comment by carrieforde** [comment]
I'd love to see this as a PR to the [WDS Components Library](https://github.com/WebDevStudios/WDS-Components-Library). Perhaps we could extend it to be a more general "cards" component with different layouts and styles? 😄

**Comment by gregrickaby** [comment]
I think it's safe to say, this needs to be simplified. The initial goal was to have equal height card styles, be a "solved problem" out of the box. I recommend we just start by adding equal height sass.

**Comment by carrieforde** [comment]
I'd personally prefer to see fewer things "baked-in" that need to be removed, and instead have these WordPress-ready styles available as drop-ins via the WDS Components Library.

Near the end of a project, it's not always easy to remember, "did we actually use this?" making it increasingly difficult to remove unused code--I'd say adding code is easier than removing it. Just my 2 cents. 😄

**Comment by gregrickaby** [comment]
I agree @carrieforde. As things are added to https://github.com/WebDevStudios/WDS-Components-Library they could be removed from wd_s.

**Comment by gregrickaby** [comment]
Funny how our projects ebb and flow...we haven't seen an equal height card, since this issue was opened.

Everyone OK with just closing this?
