### ISSUE TITLE
Update .sass-lint.yml

### ISSUE THREAD

**Issue by carrieforde** [WebDevStudios/wd_s#258]
Internally, we settled on using single quotes in our Sass, but the `.sass-lint.yml` file still cries for double quotes by default. We should update this so we don't have to update it each time we set up a new theme.

We will also need to update our property units to use our new internal standards for length measurements (when to use px, rem, and em).

**Comment by allisonplus** [comment]
Branch: [qa/lint-file](https://github.com/WebDevStudios/wd_s/tree/qa/lint-file)

Adjusted `.sass-lint.yml` file to require single quotes rather than double. Updated partials to use single quotes in pseudo-elements, strings, etc.

Updated property units in `.sass-lint.yml` file as well. Adjusted partials to use `em`s for font-size and `px` for both box-shadow and border.

**Comment by gregrickaby** [comment]
@allisonplus Sweet!!! Thanks for your help on this. Can you merge in master (there will be conflicts) and then re-submit this as a PR, please? 

 😄
