### ISSUE TITLE
Use PX on all grid items

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#272]
I know this goes against our WDS standard, but given the issues we ran into on IH, I feel like if pixels good enough for Bootstrap (and %'s for Foundation), than we should stick with a unit that doesn't compound.

**Comment by carrieforde** [comment]
I'm going to have a look into this, do some testing, and see if the kinks regarding the weirdness you experienced on IH are ironed out.

My gut says this should be fixed. We already have the `$base-context` set on the `html` on `master`, which I think was the main source of the issues you experienced. And within the [`feature/utilities-updates`](https://github.com/WebDevStudios/wd_s/tree/feature/utilities-updates) branch I have split out all the functions to ensure everything is cascading and being applied correctly.

But again, this all warrants further testing, which I'll get on and let you know what I come back with. 😄

**Comment by carrieforde** [comment]
So, I have a very similar Bourbon / Neat grid set up in my personal starter theme, and have recently run into weirdness when using `em`. So I definitely agree that we should consider canning `em`s on grids in favor of `rem` or `px`.

I'd also like propose simplifying breakpoint variables to use just a regular ol' `px` or `rem` value. So for example, `$tablet-portrait-up: 600px` instead of

```scss
$tablet-portrait-up: (
    media: 600px,
);
```

This would make it much easier to do calculations on the breakpoints, which is really helpful when using our new `media` mixin.
