### ISSUE TITLE
Reorganize and refactor Navigation

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#273]
As discussed internally, we're going to break navigation components (mobile, desktop, etc...) out into separate partials.

**Comment by gregrickaby** [comment]
Just a follow up... I refactored this on a recent project and would love to demo it. Maybe bring it into wd_s!

**Comment by jomurgel** [comment]
Branch: https://github.com/WebDevStudios/wd_s/compare/theme/navigation-refactor

I've made several changes in this branch.

- Removed the `_mobile-navigation.scss` partial which appeared to be a carry-over from the older mobile-navigataion setup.
- Created a `navigation` folder inside modules and moved navigation partials in there.
- Consolodated navigation into global (contains .menu), main, mobile (contains off-canvas) and post-navigation.
- Moved the post-navigation styles out of `_navigation.scss` into its own partial in `modules > navigation`.
- Moved the global link styles into it's own `_links.scss` partial because it's independent from any navigation (presumably) and added a transition helper.
- Removed the hamburger menu styles from `_icons.scss` both because it doesn't really belong in there and to consolidate all navigation styles into the new menus folder.
- Added support for multiple nested levels in the `mobile-menu.js`
- Added styles to rotate dropdown arrow at each level.
- Adds script to prevent body from scrolling when off-canvas navigation is open.
- Moved some of the basic container styles for the main navigation into the `_header.scss` partial to consolidate all of the structural elements.
- Fixed some positioning problems with the mobile hamburger on mobile if the admin bar was present.
- Reworked the transitions on the hamburger button to make them a little less choppy using transforms rather than absolute positioning.  Tested working still in IE11, Edge, Safari, Chrome, Firefox and Opera :grin: 

**Before**
![kapture 2017-10-03 at 8 16 47](https://user-images.githubusercontent.com/5230729/31135214-932fc52e-a821-11e7-998c-50e1d9845301.gif)

**After**
![kapture 2017-10-03 at 9 58 56](https://user-images.githubusercontent.com/5230729/31135217-9560c974-a821-11e7-8d00-000bd846301b.gif)

- Decreased the max transition duration from 0.8s to 0.5s in the transitions helper partial.  Adds transition for hamburger specifically.
- Reworked the header/nav area on desktop to fix some basic render issues.

**Before**
![screenshot 2017-10-03 09 16 52](https://user-images.githubusercontent.com/5230729/31140403-86747702-a831-11e7-97e8-6c8e6db6a0d3.png)

**After**
![screenshot 2017-10-03 11 53 16](https://user-images.githubusercontent.com/5230729/31140397-82ab23d2-a831-11e7-9900-10eada5b2e67.png)

- Removed as much fat, or consolidated as much as I could to clean things up a bit.
- Added table of contents to `_mobile-navigation.scss` partial for ease of use.

Opened issue #334 to potentially discuss moving related styles together as I did here.  Keeping nav-only buttons in with navigation vs with buttons.

Opened issue #333 to potentially discuss reworking navigation to target and add classes to each submenu level individually rather than adding a global `is-visible` class.

**Comment by gregrickaby** [comment]
@jomurgel This looks fantastic and is exactly what I had in mind. 🥇 

Go ahead and open a PR!
