### ISSUE TITLE
Revert to Neat v1.9

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#325]
After some [internal research](https://codepen.io/collection/DrjkLz/) and (lots of) discussion, we're going to revert back to [Neat v1.9](http://neat.bourbon.io/docs/1.9.0/). WDS is still planning on moving to [Foundation](https://github.com/zurb/foundation-sites/), however in the interim, we don't want to use Neat v2 any further.

The experiment with Neat v2 (along with our own presentational classes) was _less then rad_. It resulted in both build teams writing their own "on-demand grids" to solve problems. The experiment wasn't all bad, we did learn how to make some nifty helper classes, which we want to [bake in](https://github.com/WebDevStudios/wd_s/issues/326).

Bottom line: WDS FEDs just prefer to write on-demand grids. 

**Here's the plan:**

- [x] Update package.json to point exactly at Neat 1.9.0
- [x] Remove all presentational grid mixins and declarations
- [x] Comb through sass partials, and revert `@include grid-column()` to `@include span-columns()`
- [x] Do the same for `@include grid-media()`
- [x] ~Bake in some helper classes (to be provided by @efuller, in #326)~ Coming later...
- [x] Set up a basic grid for `primary` and `secondary` (like we used to have)
- [x] Add three column header (Logo/Menu/Search and or Button)
- [x] Test [Babel](https://babeljs.io/) transpiling for IE11
- [x] Test, test, test... (a11y, responsive, cbt)
- [x] Document the changes on [the wiki](https://github.com/WebDevStudios/wd_s/wiki)
- [x] Ship! :shipit: 

I've spun up a branch: https://github.com/WebDevStudios/wd_s/tree/theme/revert-neat

Contributions are welcome... Onward!

**Comment by Cheffheid** [comment]
Think the fifty/fifty block should be set up with some basic columns? I saw that the recent posts block has some to make a 3 column layout, but not fifty/fifty.

**Comment by gregrickaby** [comment]
@Cheffheid Yes, please.

**Comment by efuller** [comment]
@gregrickaby e4149b9168f4a469adc7f40f4c2eda714510f24e should take care of the testing for transpiling!

ES6 is being transpiled to ES5. Where we were running into issues was when trying to use some of the new Array methods such as `Array.from` in IE11.

To fix this I've added in `babel-polyfill` which should only load on IE.

Also, on the helper classes, since there is more discussion to be had around that, I think we could totally make it it's own thing and not let it hinder us from getting these fixes merged in ASAP. I'd rather get input/ideas from everyone rather than rush.
