### ISSUE TITLE
Document copyright_year shortcode in wiki

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#421]
Refer to https://github.com/WebDevStudios/wd_s/pull/379

**Comment by jomurgel** [comment]
Looks like this might have been documented already: https://github.com/WebDevStudios/wd_s/wiki/Extras

I did add the third example provided in #379 but otherwise looks like it's included already.

![screenshot 2018-11-27 07 55 44](https://user-images.githubusercontent.com/5230729/49089909-da937080-f219-11e8-93b2-75bbb07b5d83.jpg)

**Comment by coreymcollins** [comment]
Looks good!
