### ISSUE TITLE
Documentation: Update ACF Content Blocks

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#424]
Refer to #409

**Comment by jomurgel** [comment]
I've made several updates to the documentation [here](https://github.com/WebDevStudios/wd_s/wiki/ACF-Content-Blocks). 

Including:
- Added a new screenshot for "other options".
- Added notations for the new color picker and links to the defining functions.
- Added notations for the animation dropdown — link to animate.css.
- Added notations for the Start/End date and function.
- Centered the gif of the slider (was driving me crazy).
- Updated the recent and related post screenshots — had some exposed markup showing that was since fixed.

**Comment by coreymcollins** [comment]
Nice work! I also added screenshots of the Animation drop down options and the Date Picker since the Color Picker had screenshot and I figured it couldn't hurt since all three fields show/do something on click.

Going to close this one out – thanks!
