### ISSUE TITLE
Replace hidden elements with SRT classes & ARIA labels

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#429]
Note from Corey in #382.

> I know this is already in the theme, but I think it might be best to remove this and instead add the screen-reader-text class and ARIA labels to the entry titles of posts where we want to hide the title. Right now, the post title is hidden so on an archive page I don't have any context about the post when the screen reader gets to it.

> But maybe that's intentional? I'm not sure why these were hidden in the first place. 🤔

This seemed like an update that we should move into it's own issue as it requires discussion about original intent and an audit of elements that might also need to be updated.

**Comment by coreymcollins** [comment]
@gregrickaby do you remember at all why we are hiding post titles on archive/search results pages if they're set to Post Format "Aside"? Might just be a carry-over from `_s`, and I know we don't use Post Formats often (ever?), so I'm guessing it's something that's just been around forever.

As Jo noted above, my note in the other task was to conditionally add classes for `screen-reader-text` and set ARIA labels when we want to hide these elements rather than hiding them with CSS so screen readers can still read the post title. I can't think of why we _wouldn't_ want the post title to be discoverable by a screen reader on a page like search results.

Thoughts?

Link to the styles in question: https://github.com/WebDevStudios/wd_s/blob/master/assets/sass/modules/_content.scss#L74

**Comment by mharis** [comment]
Agreed with @coreymcollins. A hidden post title should still be screen reader accessible unless there is a post title already on the page.

Maybe this was an accident?
