### ISSUE TITLE
Feeding posts into ACF Carousel block

### ISSUE THREAD

**Issue by cseto** [WebDevStudios/wd_s#439]
I've been working on the theme as a possible option for a project. One of the requested features is a slider that displays posts of a certain category, like Recent Posts. The center mode for Slick Carousel looks exactly like what I'd want to implement for this slider. My plan was to use the ACF Carousel block but the instruction for the Carousel says up to twelve slides though. Does that mean it would not be possible to feed posts into the Carousel? Eventually the slide count would be greater than twelve.

Should I make a copy of the carousel script and content block and edit them to make it accept a custom WP_query? 

Or would it be better to create a new template that contains the slick functions and custom query, without using any of the wd_s functions?

Thanks!

**Comment by coreymcollins** [comment]
The 12-slide limit is just the number we have set for our maximum allowed repeaters in the Carousel's ACF settings:
![](https://dl.dropbox.com/s/0e8abdq31e9wr6d/Screenshot%202018-12-03%2009.05.17.jpg?dl=0)

That can be changed if you're going to need more than 12 manually-added slides for your carousels.

It sounds like what you want to do is create a carousel which displays posts from a specific category rather than manually adding posts to a carousel the way our block is set up.

So, if you want to use your category posts carousel as an ACF flexible content block, I think what you'd want to do is:
- Create a new block where the user can set the category and perhaps max number of posts to display
- Create a new template part to power that block, pulling the posts via WP Query and displaying them in a carousel

You could certainly use the code we have in place as a basis for getting your carousel up and running with the only caveat being that our JS currently targets a `.carousel` class, so you'd either need to make sure your new carousel uses the same class or update the existing JS (or create a new JS file) in the theme to use whichever class name you prefer.

**Comment by cseto** [comment]
Thanks - that is indeed my plan. Create a new block and a new template part to power that block, and probably a new JS file to keep things clean. Will update with results.
