### ISSUE TITLE
Replace bower with npm

### ISSUE THREAD

**Issue by efuller** [WebDevStudios/wd_s#453]
Find a way to use `npm` to replace Bower.

Currently, bower is used to install animate.css and normalize.css. Those files are then manually copied over into the `sass/vendor` folder.

For the solution, we need to make sure that Google doesn't count it as an external request. Importing from `node_modules` might cause this.

**Comment by efuller** [comment]
Performed some testing here today and I think as long as we can get Sass ready versions of the things we need, we should be able to eliminate Bower and rely on NPM. Making sure we have `Sass` ports will eliminate extra network requests.

**Comment by Cheffheid** [comment]
So, in an attempt to get some of these old issues wrapped up, I see three things that are being installed through Bower:

- animate.css (which is being removed in #480) 
- Slick Carousel (which is potentially being replaced, pending #481)
- normalize (which seems to be replaced by sanitize.css in #442)

So with all that said, and #480 being merged in today, I think the plan to ditch Bower going forward should probably be:

- Update #481 to use NPM instead of Bower to install Tiny Slider.
- Remove `.bowerrc` and `bower.json` files, as well as https://github.com/WebDevStudios/wd_s/tree/7434d33382484b9efd917769e1b47911759834df/assets/bower_components
- Split our NPM packages and properly set up dependencies and dev dependencies (which, I think, everything in package.json is currently a dev dependency)
- Update Buddy to run `npm install` and install the dependencies
- Update the README to update the npm/yarn commands to include `--only=dev`/`--dev` and remove references to Bower
