### ISSUE TITLE
Slick Slider support and accessibility features

### ISSUE THREAD

**Issue by cseto** [WebDevStudios/wd_s#460]
Slick hasn't been getting updates and I was wondering if that has any effect on keeping up with accessibility requirements, like in this example https://github.com/kenwheeler/slick/issues/3684

**Comment by Cheffheid** [comment]
Personally, I would probably want to nix carousels altogether. There is too much potential of creating something that is poorly accessible and ultimately they are mostly useless in getting people to read the content anyway.

Even if the script itself provides you with the means to make it abide by the standards, all you'd really need to do is disable the pause button on one that changes slides automatically "because it doesn't have one in the design".

However, the issues outlined in that ticket can probably be tackled by hooking into the events that a Slick carousel fires. Similarly, it has a method to pause a carousel so adding our own pause button shouldn't be too much of an issue either. And so that may be the way to go while I get off my carousel soap box. :)

**Comment by cseto** [comment]
I get on the soap box too. The sorts of design changes that come down knock a carousel out of compliance pretty quickly. Additionally, once a site is handed off, it is difficult to ensure compliance to accessibility. 

Is the version of Slick used in-theme good enough in spite of its discontinued support (although there are recent efforts to maintain a fork) or should there be an different slider considered for the carousel?

**Comment by Cheffheid** [comment]
I _think_ so, but we'd need to do some testing for that to see if there are any other issues we may uncover. I'm also not familiar with a good replacement either.

I did put some effort into putting in a pause button, and using wp.a11y.speak to get some screen reader notifications going today while we consider the greater accessibility audit of Slick and whether we'd want to replace it or not.
