### ISSUE TITLE
Utilize WYSIWYG in ACF Fields More

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#473]
In working on some client projects and generally, I wonder if we wouldn't better serve the client/user to replace any instances in which we utilize a Title/Text combo with a WYSIWYG.

Some examples of this are:
- Hero
- Carousel
- CTA

The only place that this makes sense is the Accordion block since the title is used externally from the content.

I also wonder if we wouldn't also potentially add some additional TinyMCE styles for inline buttons, etc. Though utilizing Gutenberg in the future make this a moot point.

**Comment by coreymcollins** [comment]
I go back and forth on the WYSIWYG in favor of the title/content blocks. I see the positive side of it, but also see the potential for doing something truly heinous in the editor and adding broken markup, inline styles, etc.

Using the individual fields safeguards, to a degree, because they'll always be title and content. It kind of helps us as devs because we know exactly what to plan and code for and helps the client/user because they can't accidentally do anything wrong.

I think I could really go either way on this, though, and would love more feedback from the team to see how everyone else feels about it.

**Comment by Cheffheid** [comment]
While I'm not completely against using WYSIWYG editors more, I do want to err on the side of caution here. Giving people this kind of freedom and flexibility is a good way for clients to find ways to break things.

At the very least, it means that we'll need to decide on what tags to allow and what tags to not allow to stop things like iframes and who knows what else (I'm not sure what `wp_kses_post` allows though, so it may not be as bad as I think it is).

But also,
![arj8me](https://user-images.githubusercontent.com/1461585/53840626-9e825100-3f68-11e9-9d5a-d2a4bac531ca.gif)

The power of the WYSIWYG editor: 
https://www.cookwithcampbells.ca/articles/make-holiday-leftovers/

**Comment by coreymcollins** [comment]
Going to close this out. We'll continue to operate as we do, using WYSIWYG where it makes sense but not really making a rule one way or the other. It's good to have some safeguards, like knowing Field X is always going to have `h2` markup versus a free-for-all with a WYSIWYG.
