### ISSUE TITLE
Stylelint is not enforcing alphabetical sorting with the new coding standards

### ISSUE THREAD

**Issue by itsamoreh** [WebDevStudios/wd_s#538]
See title. Linting is working because other rules are being enforced.

Was the alpha sorting rule removed?

![ 2020-06-25 at 10 47 47 ](https://user-images.githubusercontent.com/12365909/85742537-5218d280-b6d1-11ea-813c-056f89f26384.png)

**Comment by aubreypwd** [comment]
I got on with @itsamoreh and reviewed this, and the theme is not running `@webdevstudios/css-coding-standards` but is running it's own `stylelint` based rules. I would have expected the alpha-sorting to be a rule (as it's a rule in `css-coding-standards`), but maybe that has changed?

**Comment by coreymcollins** [comment]
It looks like we all may have been getting some false positives/false passes because we all had globals installed in addition to the theme-specific setup. Aubrey and I just chatted and it seems like the best plan forward to avoid going back to installing the old globals is to build out the `stylelintrc.js` file with all of our rules.

**Comment by coreymcollins** [comment]
Going to tag #542 here as I think the work done as a result of that issue will resolve this as well.
