### ISSUE TITLE
Use style.css version for asset cache busting

### ISSUE THREAD

**Issue by tarecord** [WebDevStudios/wd_s#565]
We are defining the theme’s version number for cache busting with enqueued scripts/styles in [inc/scripts.php](https://github.com/WebDevStudios/wd_s/blob/46a3d005a9e3f8841b5f2db9bbd161c82f9cf940/inc/scripts.php#L27). Would it be simpler to grab the version of the current stylesheet? It would reduce the number of locations we need to address the version.
```php
$version = ( wp_get_theme() )->get( 'Version' );
```
Additionally, we could provide debugging.
```php
$version = ( true === $debug ) ? time() : ( wp_get_theme() )->get( 'Version' );
```

**Comment by coreymcollins** [comment]
It looks like that `$version` variable is leftover from a previous change, and we never removed it. Right now we grab the version numbers based on the build files:

```
wp_enqueue_style( 'wd_s', get_stylesheet_directory_uri() . '/build/index.css', array(), $asset_file['version'] );
wp_enqueue_script( 'wds-scripts', get_stylesheet_directory_uri() . '/build/index.js', $asset_file['dependencies'], $asset_file['version'], true );
```

This happens in the `build/index.asset.php` file:
```
return array('dependencies' => array('wp-polyfill'), 'version' => '8e0994a6466a360a478f428058380af4');
```

With this, we don't need to manually change anything as the version will update every time a build happens. I don't know that we'd want to grab the version number from the theme/main stylesheet since we don't really release the theme in versions in that way.
