### ISSUE TITLE
WP-CLI Scaffold

### ISSUE THREAD

**Issue by jrfoell** [WebDevStudios/wd_s#593]
While looking at using WP-CLI plugin scaffolding to replace/augment our plugin generator, I noticed there's also this command

`wp scaffold _s`
from https://developer.wordpress.org/cli/commands/scaffold/

Thinking we could possibly provide a `wp scaffold wd_s` that does the same thing as our https://wdunderscores.com/ site.

**Comment by gregrickaby** [comment]
💯  

The Gutenberg team has also created a PHP-based script for generating themes which is def worth a look.

```bash
php new-empty-theme.php
```

https://github.com/WordPress/theme-experiments/blob/master/new-empty-theme.php

**Comment by donmhico** [comment]
In my efforts on this ticket, I created https://github.com/donmhico/wd_s-scaffold . It's very simple at the moment but it does work.

I'll migrate it to a proper WDS repo at least when the following are resolved:
1. This merge - https://github.com/WebDevStudios/wd_s-generator/commit/d3bbb4c59c4d3defbae8ea042753c4ecd338ceee - was undone / regressed due to Buddy. This needs to be pushed to production.
1. Add the remaining theme data as command args (e.g. `theme_uri`, `author_uri`, etc.). Fix the point above first.
1. Fix this issue https://github.com/donmhico/wd_s-scaffold/issues/1

**Comment by gregrickaby** [comment]
@donmhico I'll look into the deployment regression. Might be a good time to switch from Buddy to Github Actions.

**Comment by donmhico** [comment]
Thanks @gregrickaby. I'll circle back to this once the deployment regression is fixed.

**Comment by gregrickaby** [comment]
@donmhico I just re-ran Buddy. Can you verify? Thanks.

**Comment by donmhico** [comment]
@gregrickaby It's working now thank you! I'll continue on this when time permits.
