### ISSUE TITLE
Sometimes the fonts in /build will get deleted by npm

### ISSUE THREAD

**Issue by oliverharrison** [WebDevStudios/wd_s#693]
I will update this ticket as I have more evidence to help you track this down. However, this is essentially what happens:

* Run `npm run start`
* Verify that the custom fonts (added as per the wiki) are in /build/fonts/fontnames.woff
* Continue coding
* Eventually, the custom fonts might disappear from the /build folder
* npm watch continues without rebuilding the fonts
* Run nmp run build to re-build the fonts and continue

**Comment by coreymcollins** [comment]
I can replicate the font erasure issue if I add an image to the `src/images/` directory. Everything is fine if I add an SVG to `src/images/svg`, but if I add an image to (or remove an image from) the top-level `/images/` directory, some of the fonts disappear.

On initial `npm run build` I wind up with my first screenshot above with basically duplicate font files – one named normally, then one with an string at the end.

While `npm run start` is running and I add an image, the extra string fonts are removed and the regular string ones remain.

I think this issue stems from Clean Webpack Plugin. We use that to clean our build directory so we don’t keep old/deleted files, and it works great and does its job. But, Tailwind wants to create font files itself and it does so with a string at the end like `/raleway-medium-webfont.06ef4a38.woff2`

It also changes the src in the built CSS file to match `src: local("Raleway Medium"), url(fonts/raleway-medium-webfont.06ef4a38.woff2) format("woff2");`

So when the Clean Webpack Plugin happens, it  cleans our build directory (good), but Tailwind doesn’t regenerate its font files on `npm run start` (bad) which means we don’t get those fonts regenerated (bad) which means the built CSS file is now pointing to files that don’t exist (bad).

**Comment by coreymcollins** [comment]
For like a very iffy workaround, you can do this
```
new CleanWebpackPlugin( {
    cleanAfterEveryBuildPatterns: ['!fonts/**', '!*.woff2'],
} ),
```

This will ignore anything in `build/fonts` and any `*.woff2` files in the build directory (just to be safe, I guess). This will still add new fonts to your build directory if you add them to your `src` while running `npm run start`, but it won’t remove anything from `build` if you remove it from `src` and won't actually create the Tailwind versions of the files. It'll just do the basic CopyWebpackPlugin thing of copying the file.

If you run a full `npm run build`, it seems like it generates all of the fonts that should be there (so far). Might not want to push your webpack config changes to a dev site or anywhere else, but may be a good workaround for locals since you shouldn’t really need to add too many new fonts mid-project anyway?

Still going to look into this some more.

**Comment by coreymcollins** [comment]
So, the above addition to `CleanWebpackPlugin` works with the following caveats:
- Build fonts are **only** regenerated on `npm run build`
- If you add or remove a font from the `/src/fonts` directory while running `npm run start` or `npm run watch`, **nothing changes** – fonts are not added or removed because of the `cleanAfterEveryBuildPatterns` ignore rule

I'm not sure if this is necessarily a blocker for our workflow? As I mentioned above, you generally aren't adding new fonts halfway through a project so you shouldn't have to be swapping fonts in and out all the time while running `npm run start` or anything in your daily flow.

Plus, knowing that the build directory **does** get cleaned and rebuilt (including `/build/fonts` means that fonts _should_ always be doing what we expect them to be doing on lab/production since `npm run build` doesn't seem to be confined by the `cleanAfterEveryBuildPatterns` ignore rule.

I'll see about getting a PR spun up for this later this morning, and this will need extensive testing, but hopefully this solves the disapearing font issue or at least leads us down a path to solving it.

**Comment by coreymcollins** [comment]
So, the above addition to `CleanWebpackPlugin` works with the following caveats:
- Build fonts are **only** regenerated on `npm run build`
- If you add or remove a font from the `/src/fonts` directory while running `npm run start` or `npm run watch`, **nothing changes** – fonts are not added or removed because of the `cleanAfterEveryBuildPatterns` ignore rule

I'm not sure if this is necessarily a blocker for our workflow? As I mentioned above, you generally aren't adding new fonts halfway through a project so you shouldn't have to be swapping fonts in and out all the time while running `npm run start` or anything in your daily flow.

Plus, knowing that the build directory **does** get cleaned and rebuilt (including `/build/fonts` means that fonts _should_ always be doing what we expect them to be doing on lab/production since `npm run build` doesn't seem to be confined by the `cleanAfterEveryBuildPatterns` ignore rule.

I'll see about getting a PR spun up for this later this morning, and this will need extensive testing, but hopefully this solves the disapearing font issue or at least leads us down a path to solving it.
