### ISSUE TITLE
Admin style conflicts

### ISSUE THREAD

**Issue by JaketheYeti** [WebDevStudios/wd_s#795]
Hello,

Some admin styles seem to be getting overridden by the main stylesheet - even when I comment out the lines in the inc/setup.php to add theme support for editor-styles. 

Can be seen in the customizer (fonts, overflow, and list items are affected, from what I can see), and in the gutenberg post editor (checkboxes and list items are affected, from what I can see).

I've attached comparisons between TwentyTwentyOne theme and WD_S (with minimal changes)
![Customizer - 2021 theme](https://user-images.githubusercontent.com/93015244/143267297-20c46056-5060-44a0-aa8b-d88f4f9b43cf.jpg)
![customizer - wd_s](https://user-images.githubusercontent.com/93015244/143267305-8ada514f-831c-4336-ab21-907e91c01f9d.jpg)
![Gutenberg - 2021 theme](https://user-images.githubusercontent.com/93015244/143267307-524c6c26-ab03-4900-9d30-bddbcbcf18ce.jpg)
![gutenberg wd_s theme](https://user-images.githubusercontent.com/93015244/143267309-3d342d69-593e-415b-8afd-87b151c48207.jpg)
.

I can change the styles one by one as I notice them, but I'd rather just remove the styles from loading for these pages.

**Comment by coreymcollins** [comment]
I think this is going to depend on what you're adding in your styles and how.

For instance, if I add a new font to my theme I'm not seeing anything change in the Customizer in the way you are:
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/954724/143299264-373d902d-093e-458a-beff-69a1a2796612.png">

However, the styles are included in _just_ the editor since they're being added as editor styles:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/954724/143299333-558aa8e3-ad65-4111-983e-ef195e81f197.png">

The theme doesn't enqueue full-on admin/dashboard styles, just editor styles.

**Comment by JaketheYeti** [comment]
Hi Corey,
Thanks for your reply! I did some digging, and it seems to be coming from the WDS ACF block plugins, not the theme. I apologize, I should have checked the plugins first!
